version: "3.3"
services:
  all:
    build: .
    image: 'weibo_all:2'
    command: python3 main.py
    restart: unless-stopped
  web:
    build: .
    environment:
      - FLASKAPP=flaskr
    ports: 
      - 8089:8089 
    image: 'weibo_web:2'
    command: flask run --host 0.0.0.0 --port 8089
    restart: unless-stopped