version: "3.3"
services:
  all:
    build: .
    image: 'weibo_all:2'
    container_name: weibo_all
    environment:
      - DBIP=192.168.2.103
      - MINIOIP=192.168.2.107
      - DBPort=27017
      - MINIOPort=9010
    depends_on:
      - mongodb
    command: python3 task_all.py
    # restart: unless-stopped
    networks:
      - node-network
  follow:
    build: .
    image: 'weibo_follow:2'
    container_name: weibo_follow
    environment:
      - DBIP=192.168.2.103
      - MINIOIP=192.168.2.107
      - DBPort=27017
      - MINIOPort=9010
    depends_on:
      - mongodb
    command: python3 task_follow.py
    # restart: unless-stopped
    networks:
      - node-network
  my:
    build: .
    image: 'weibo_my:2'
    container_name: weibo_my
    environment:
      - DBIP=192.168.2.103
      - MINIOIP=192.168.2.107
      - DBPort=27017
      - MINIOPort=9010
    depends_on:
      - mongodb
    command: python3 task_my.py
    # restart: unless-stopped
    networks:
      - node-network
  hot:
    build: .
    image: 'weibo_hot:2'
    container_name: weibo_hot
    environment:
      - DBIP=192.168.2.103
      - MINIOIP=192.168.2.107
      - DBPort=27017
      - MINIOPort=9010
    depends_on:
      - mongodb
    command: python3 task_hot.py
    # restart: unless-stopped
    networks:
      - node-network
  state:
    build: .
    image: 'weibo_state:2'
    container_name: weibo_state
    environment:
      - DBIP=192.168.2.103
      - MINIOIP=192.168.2.107
      - DBPort=27017
      - MINIOPort=9010
    depends_on:
      - mongodb
    command: python3 task_state.py
    # restart: unless-stopped
    networks:
      - node-network
  proxy:
    build: .
    image: 'weibo_proxy:2'
    container_name: weibo_proxy
    environment:
      - DBIP=192.168.2.103
      - MINIOIP=192.168.2.107
      - DBPort=27017
      - MINIOPort=9010
    depends_on:
      - mongodb
    command: python3 task_proxy.py
    # restart: unless-stopped
    networks:
      - node-network
  web:
    build: .
    environment:
      - FLASKAPP=flaskr
      - DBIP=192.168.2.103
      - MINIOIP=192.168.2.107
      - DBPort=27017
      - MINIOPort=9010
    ports: 
      - 8089:8089 
    image: 'weibo_web:2'
    container_name: weibo_web
    depends_on:
      - mongodb
    command: flask run --host 0.0.0.0 --port 8089
    restart: unless-stopped
  mongodb:
    image: mongo:2
    container_name: weibo_mongo
    ports:
      - '27017:27017'
    networks:
      - node-network

networks:
  node-network:
    driver: bridge